version: 0.0
os: linux
files:
  - source: /
    destination: /var/id-service/
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
  AfterInstall:
    - location: scripts/initService.sh
      timeout: 60
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60