version: 0.0
os: linux
files:
  - source: build/libs
    destination: /opt/id-service
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/createService.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 30
      runas: root
